### DISCUSSION TITLE
Proposal for framework usage and configuration

### DISCUSSION THREAD

**Discussion by miguelafsilva5** [bao-project/bao-tests#5] [Ideas]
Hello,

As we have discussed in previous meetings, me and @Diogo21Costa were to propose the organization of our framework across all bao components.
We assume that our repo is to be added across all bao elements, similarly to the ci repo. 
Taking this into consideration our proposed directory organization is the following:  (- is a directory and * is a file)

```
- baremetal (example Module under test)
 - bao-tests (our repo)
    - templates
        * config_template.yaml
    - framework
        * **config.yaml**    (personal configuration file for toolchains and paths. should be added to gitignore)
    - build <---- add to gitignore
        * img.bin (output from compile and tool)
 - src (defaul on all repos)
    - tests (this directory can be configured in the config.yaml, but this is our default suggestion)
        - src
            * ABCD.c (files with test implementation)
            * XPTO.c
        - example
            * **example.yaml** (test battery descriptor)
            * config.tool (envisioned file to configure/use the tool to generate the remaining bao stack binaries)
```

Lastly, the we have two suggestions for the highlighted .yaml files (config.yaml and example.yaml).
The config.yaml is to filled by each developer with their own directoy path. From early discussions, we established that all directories must absolute, and thus, such a file is needed. This is what we propose:

```
bao_test_cfg:
  bao_test_dir: /path/to/bao-tests/dir  (to be removed later)
  tests_dir: /home/usr/bao/baremetal/src/tests

platform_cfg:
  platforms:
    qemu-aarch64-virt:
      toolchain: /path/to/toolchain
    qemu-riscv64-virt:
      toolchain: /path/to/toolchain
     zcu102:
      toolchain: /path/to/toolchain
    
```

The example.yaml file should be placed inside a folder on the path defined in _tests_dir_. The folder represents a group of tests (battery). These tests can be configured in a single yaml file or in multiple files. The idea is to allow the developer to group their tests, and use multiple yaml files to differentiate tests running in different platforms, for instance.
(Note that when running our framework a battery name should be provided, e.g., make run example)

```
tests_cfg:
  log_level: int_log_level

  platforms:
    qemu-aarch64-virt
    zcu102

  suites:
    ABCD:
        - ABCD_test1_name
        - ABCD_test2_name
    XPTO:
        - XPTO_test1_name
    SUITE1: all
```

If you have any suggestions or see any problems, feel free to discuss.

Thank you,
Miguel Silva

@bao-project/core
